.TH "shell/2.ft_execve.c" 3 "Pipex" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shell/2.ft_execve.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pipex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_my_getenv_\fP (char *cmd, char **env)"
.br
.ti -1c
.RI "char * \fBft_my_getenv\fP (char *name, char **env)"
.br
.ti -1c
.RI "void \fBft_execve\fP (char *cmd, char **env)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_execve (char * cmd, char ** env)"

.SS "char * ft_my_getenv (char * name, char ** env)"

.SS "char * ft_my_getenv_ (char * cmd, char ** env)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pipex from the source code\&.
