.TH "utils/3.error_handling.c" 3 "Pipex" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils/3.error_handling.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pipex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBerror_handling_pipex\fP (int argc)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void error_handling_pipex (int argc)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pipex from the source code\&.
